apiVersion: v1
kind: ConfigMap
metadata:
  name: designer-api-config
  namespace: {{ .Values.namespace }}
data:
  DESIGNER_LOG_LEVEL: "DEBUG"
  DESIGNER_ACCESS_LOG_ENABLE: "true"
  QUARKUS_PROFILE: "prod"
  DESIGNER_API_URL: "/apis/designer/v0"
  DESIGNER_CORS_ALLOWED_ORIGINS: "*"
  AUTH_ENABLED: "true"
  OIDC_TOKENT_ENDPOINT: "{{ .Values.auth.url }}/realms/{{ .Values.auth.realm }}"
  OIDC_URL: "{{ .Values.auth.url }}/realms/{{ .Values.auth.realm }}"
  OIDC_API_CLIENT_ID: "designer-api"
  DESIGNER_STORAGE_DATASOURCE_URL: "jdbc:postgresql://apicurio-designer-postgresql:5432/apicuriodb"
  DESIGNER_STORAGE_DATASOURCE_USERNAME: "pguser"
  DESIGNER_STORAGE_DATASOURCE_PASSWORD: "pgpass12345"