{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin
type: Opaque
data:
  KEYCLOAK_ADMIN: {{ .Values.auth.secret.adminUsername | b64enc | quote }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.auth.secret.adminPassword | b64enc | quote }}
{{- end }}
