apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apicurio-registry
    component: apicurio-registry-ui
  name: apicurio-registry-ui
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.registry.ui.replicaCount }}
  selector:
    matchLabels:
      component: apicurio-registry-ui
  template:
    metadata:
      labels:
        app: apicurio-registry
        component: apicurio-registry-ui
    spec:
      containers:
      - image: quay.io/apicurio/apicurio-registry-ui:latest-snapshot
        name: apicurio-registry-ui
        ports:
          - name: web
            containerPort: 8080
            protocol: TCP
        envFrom:
          - configMapRef:
              name: registry-ui-config
        resources:
{{ toYaml .Values.registry.ui.resources | indent 12 }}
        livenessProbe:
          httpGet:
            path: /config.js
            port: 8080
            scheme: HTTP
{{ toYaml .Values.registry.ui.livenessProbe | indent 12 }}
        readinessProbe:
          httpGet:
            path: /config.js
            port: 8080
            scheme: HTTP
{{ toYaml .Values.registry.ui.readinessProbe | indent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: apicurio-registry
    template: apicurio-registry-ui
  name: apicurio-registry-ui
spec:
  selector:
    component: apicurio-registry-ui
  ports:
    - name: web
      port: 8080
      protocol: TCP
      targetPort: 8080
  type: ClusterIP
---
{{- if .Values.registry.ui.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: apicurio-registry
    template: apicurio-registry-ui
  name: apicurio-registry-ui
spec:
  # {{- if and .Values.ingress.ingressClassName (eq "true" (include "common.ingress.supportsIngressClassname" .)) }}
  # ingressClassName: {{ .Values.ingress.ingressClassName | quote }}
  # {{- end }}
  rules:
    - host: {{ .Values.registry.ui.ingress.host }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: apicurio-registry-ui
                port:
                  number: 8080
{{- end }}