receivers:
    otlp:
        protocols:
            grpc:
                endpoint: otel-collector:4317

exporters:
    jaeger:
        endpoint: jaeger:14250
        tls:
            insecure: true
    zipkin:
        endpoint: "http://zipkin:9411/api/v2/spans"
        format: proto


processors:
    batch:

extensions:
    health_check:
    pprof:
        endpoint: :1888
    zpages:
        endpoint: :55679

service:
    extensions:
        - health_check
    pipelines:
        traces:
            receivers:
                - otlp
            processors:
                - batch
            exporters:
                - jaeger
