yamlApplicationConfig:
  kafka:
    clusters:
      - name: yaml
        bootstrapServers:  redpanda-0.redpanda.redpanda.svc.cluster.local:9092
  auth:
    type: disabled
  management:
    health:
      ldap:
        enabled: false
