apiVersion: redpanda.vectorized.io/v1alpha1
kind: Cluster
metadata:
  name: redpanda
  namespace: redpanda
spec:
  kafkaEnableAuthorization: false
  image: "vectorized/redpanda"
  version: "latest"
  replicas: 1
  resources:
    requests:
      cpu: 1
      memory: 0.5Gi
    limits:
      cpu: 1
      memory: 1.2Gi
  additionalConfiguration:
    redpanda.cluster_id: crazyfly
    redpanda.enable_idempotence: "true"
  configuration:
    autoCreateTopics: true
    rpcServer:
      port: 33145
    kafkaApi:
    - port: 9092
      authenticationMethod: none
      # tls:
      #    enabled: true
      #    requireClientAuth: true
    - external:
        enabled: true
        subdomain: local.rp
      port: 30001
    pandaproxyApi:
    - port: 8082
      # tls:
      #    enabled: true
      #    requireClientAuth: true
    schemaRegistry:
      port: 8081
      # tls:
      #    enabled: true
      #    requireClientAuth: true
      external:
        enabled: true
        subdomain: local.rp
    adminApi:
    - port: 9644
      # tls:
      #    enabled: true
      #    requireClientAuth: true
    developerMode: true