apiVersion: registry.apicur.io/v1
kind: ApicurioRegistry
metadata:
  name: apicurio-registry
spec:
  configuration:
    kafkasql:
      bootstrapServers: 'redpanda-0.redpanda.redpanda.svc.cluster.local:9092'
