apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
spec:
#   ingress:
    # enabled: false
  instances: 1
  db:
    vendor: postgres
    host: postgresql-db
    usernameSecret:
      name: postgres-secret
      key: username
    passwordSecret:
      name: postgres-secret
      key: password
  http:
    httpEnabled: true
    tlsSecret: crazyfly-tls-secret
  hostname:
    hostname: dev.crazyfly.com
    strict: false
    strictBackchannel: false
