apiVersion: redpanda.vectorized.io/v1alpha1
kind: Cluster
metadata:
  name: redpanda
  namespace: redpanda
spec:
  image: "vectorized/redpanda"
  version: "latest"
  replicas: 1
  resources:
    requests:
      cpu: 1
      memory: 0.5Gi
    limits:
      cpu: 1
      memory: 1.2Gi
  additionalConfiguration:
    redpanda.cluster_id: crazyfly
  configuration:
    autoCreateTopics: true
    rpcServer:
      port: 33145
    kafkaApi:
    - port: 9092
      # tls:
      #    enabled: true
      #    requireClientAuth: true
    - external:
        enabled: true
        subdomain: local.rp
      port: 30001
    pandaproxyApi:
    - port: 8082
      # tls:
      #    enabled: true
      #    requireClientAuth: true
    schemaRegistry:
      port: 8081
      # tls:
      #    enabled: true
      #    requireClientAuth: true
      external:
        enabled: true
        subdomain: local.rp
    adminApi:
    - port: 9644
      # tls:
      #    enabled: true
      #    requireClientAuth: true
    developerMode: true
---
apiVersion: redpanda.vectorized.io/v1alpha1
kind: Console
metadata:
  name: console
  namespace: redpanda
spec:
  server:
    listenPort: 8080
  schema:
    enabled: true
  clusterRef:
    name: redpanda
    namespace: redpanda
  deployment:
    image: vectorized/console
  connect:
    enabled: true
    clusters:
    - name: console-connector
      url:  http://localhost:8083
    #   tls:
    #     enabled: true
    #     secretKeyRef:
    #       name: connector-tls
    #       namespace: default
