globalProperties:
    apis: "false"
    invokers: "false"
    models: ""
    supportingFiles: ""
    modelTests: "false"
    generateModelDocumentation: "false"
    generateModelTests: "false"
    library: "quarkus"

additionalProperties:
    artifactId: kotlin-petstore-client
    serializableModel: "true"
    dateLibrary: java8
    hideGenerationTimestamp: true
    useBeanValidation: false
    serializationLibrary: "jackson"
    useSwaggerAnnotations: false
    apiFirst: true
    library: "quarkus"
