# Default values for apicurio.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: apicurio
  registry: docker.io
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

namespace: "apicurio"

auth:
  enabled: true
  url: keycloak.keycloak.svc.cluster.local/realms/apicurio

designer:
  ui:
    replicaCount: 1
    image:
      repository: quay.io/apicurio/apicurio-api-designer-ui
      tag: latest-snapshot
      pullPolicy: IfNotPresent
    ingress:
      enabled: true
      host: designer.local
    resources:
      limits:
        cpu: 400m
        memory: 800Mi
      requests:
        cpu: 100m
        memory: 250Mi
    livenessProbe:
      initialDelaySeconds: 10
      timeoutSeconds: 5
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 3
    readinessProbe:
      initialDelaySeconds: 10
      timeoutSeconds: 5
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 3
  api:
    replicaCount: 1
    image:
      repository: quay.io/apicurio/apicurio-api-designer-sql
      tag: latest-snapshot
      pullPolicy: IfNotPresent
    ingress:
      enabled: true
      host: designer-api.local
    resources:
      limits:
        cpu: 500m
        memory: 1000Mi
      requests:
        cpu: 100m
        memory: 500Mi
    livenessProbe:
      initialDelaySeconds: 10
      timeoutSeconds: 5
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 3
    readinessProbe:
      initialDelaySeconds: 10
      timeoutSeconds: 5
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 3

registry:
  ui:
    replicaCount: 1
    image:
      repository: quay.io/apicurio/apicurio-registry-ui
      tag: latest-snapshot
      pullPolicy: IfNotPresent
    ingress:
      enabled: true
      host: designer.local
    resources:
      limits:
        cpu: 250m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    livenessProbe:
      initialDelaySeconds: 5
      timeoutSeconds: 5
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 3
    readinessProbe:
      initialDelaySeconds: 5
      timeoutSeconds: 5
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 3

  api:
    replicaCount: 1
    image:
      repository: quay.io/apicurio/apicurio-registry-sql
      tag: latest-snapshot
      pullPolicy: IfNotPresent
    ingress:
      enabled: true
      host: designer-api.local
    resources:
      limits:
        cpu: 500m
        memory: 1000Mi
      requests:
        cpu: 100m
        memory: 500Mi
    livenessProbe:
      initialDelaySeconds: 10
      timeoutSeconds: 5
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 3
    readinessProbe:
      initialDelaySeconds: 10
      timeoutSeconds: 5
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 3

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
